services:
  web:
    image: antonio24073/moodle:4.5-${WEBSERVER}
    container_name: moodle_web
    ports:
      - "80:80"
    volumes:
      - ./vol/moodle/html:/var/www/html
      - ./vol/moodle/config.mariadb.php:/var/www/html/config.php
      - ./vol/moodle/data:/var/www/moodledata
      - ./vol/phpu/data:/var/www/phpu_moodledata
    depends_on:
      - db
    networks:
      - moodle_network

  db:
    image: mariadb:10.6
    container_name: moodle_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=vaed3ui4yae4Vu
      - MARIADB_DATABASE=moodle
      - MARIADB_USER=moodleuser
      - MARIADB_PASSWORD=meeF9av3geegh9
      - TZ=America/Sao_Paulo
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./vol/mariadb/data:/var/lib/mariadb
      - ./vol/mariadb/my.cnf:/etc/my.cnf
      - ./vol/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize the database with the custom SQL script
    networks:
      - moodle_network

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: moodle_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=moodleuser
      - PMA_PASSWORD=meeF9av3geegh9
      - PMA_DATABASE=moodle
      - MARIADB_ROOT_PASSWORD=rootpassword
    depends_on:
      - db
    networks:
      - moodle_network

  phpu_db:
    image: mariadb:10.6
    container_name: phpunit_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=waiX4Xeih3uwed
      - MARIADB_DATABASE=phpu
      - MARIADB_USER=phpu
      - MARIADB_PASSWORD=aecaathah9heiP
      - TZ=America/Sao_Paulo
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./vol/phpu/mariadb/data:/var/lib/mariadb
      - ./vol/phpu/mariadb/my.cnf:/etc/my.cnf
      - ./vol/phpu/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize the database with the custom SQL script
    networks:
      - moodle_network

  phpu_pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpunit_phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=phpu_db
      - PMA_DATABASE=phpu
      - PMA_USER=phpu
      - PMA_PASSWORD=aecaathah9heiP
      - MARIADB_ROOT_PASSWORD=waiX4Xeih3uwed
    depends_on:
      - db
    networks:
      - moodle_network

networks:
  moodle_network: