services:
  web:
    image: ${REPO}-${WEBSERVER}
    container_name: ${STACK}_moodle_web
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - ./vol/moodle/html:/var/www/html
      - ./vol/moodle/config.mysql.php:/var/www/html/config.php
      - ${MOODLEDATA_DIR}:/var/www/moodledata
      - ./vol/phpu/data:/var/www/phpu_moodledata
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PREFIX=${MYSQL_PREFIX}
      - MYSQL_PORT=${MYSQL_PORT}
      - SERVERURL=${SERVERURL}
      - WWWROOT=${WWWROOT}
      - SERVERURL=${SERVERURL}
      - WWWROOT=${WWWROOT}
      - PHPU_ENABLED=${PHPU_ENABLED}
      - PHPU_MYSQL_PREFIX=${PHPU_MYSQL_PREFIX}
      - PHPU_MYSQL_DATABASE=${PHPU_MYSQL_DATABASE}
      - PHPU_MYSQL_USER=${PHPU_MYSQL_USER}
      - PHPU_MYSQL_PASSWORD=${PHPU_MYSQL_PASSWORD}
    command: > 
      sh -c "
      sed -i -e 's/Listen 80/Listen ${WEB_PORT}/g' /etc/apache2/ports.conf || true &&
      sed -i -e 's/<VirtualHost *: 80>/<VirtualHost *: ${WEB_PORT}>/g' /etc/apache2/sites-enabled/000-default.conf || true &&
      sed -i -e 's/listen 80;/listen ${WEB_PORT};/g' /etc/nginx/sites-available/moodle || true &&
      echo \"<Directory /var/www/html>
          AllowOverride All
      </Directory>\" >> /etc/apache2/sites-enabled/000-default.conf &&
      sh /cmd.sh
      "
    depends_on:
      - db
    networks:
      - moodle_network

  db:
    image: mysql:8.0
    container_name: ${STACK}_moodle_db
    restart: always
    ports:
      - "${MYSQL_DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${MYSQL_TZ}
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./vol/mysql/data:/var/lib/mysql
      - ./vol/mysql/my.cnf:/etc/my.cnf
      - ./vol/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - moodle_network

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${STACK}_moodle_phpmyadmin
    restart: always
    ports:
      - "${MYSQL_PMA_PORT}:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=${MYSQL_PMA_USER}
      - PMA_PASSWORD=${MYSQL_PMA_PASSWORD}
      - PMA_DATABASE=${MYSQL_PMA_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - moodle_network

  phpu_db:
    image: mysql:8.0
    container_name: ${STACK}_moodle_phpunit_db
    restart: always
    ports:
      - "${MYSQL_PHPU_DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${PHPU_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${PHPU_MYSQL_DATABASE}
      - MYSQL_USER=${PHPU_MYSQL_USER}
      - MYSQL_PASSWORD=${PHPU_MYSQL_PASSWORD}
      - TZ=${PHPU_MYSQL_TZ}
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./vol/phpu/mysql/data:/var/lib/mysql
      - ./vol/phpu/mysql/my.cnf:/etc/my.cnf
      - ./vol/phpu/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - moodle_network

  phpu_pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${STACK}_moodle_phpunit_phpmyadmin
    restart: always
    ports:
      - "${MYSQL_PHPU_PMA_PORT}:80"
    environment:
      - PMA_HOST=phpu_db
      - PMA_DATABASE=${PHPU_MYSQL_PMA_DATABASE}
      - PMA_USER=${PHPU_MYSQL_PMA_USER}
      - PMA_PASSWORD=${PHPU_MYSQL_PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PHPU_MYSQL_ROOT_PASSWORD}
    depends_on:
      - phpu_db
    networks:
      - moodle_network

networks:
  moodle_network:
