services:
  web:
    image: antonio24073/moodle:4.5-${WEBSERVER}
    container_name: moodle_web
    ports:
      - "80:80"
    volumes:
      - ./vol/moodle/html:/var/www/html
      - ./vol/moodle/config.mysql.php:/var/www/html/config.php
      - ./vol/moodle/data:/var/www/moodledata
      - ./vol/phpu/data:/var/www/phpu_moodledata
    depends_on:
      - db
    networks:
      - moodle_network

  db:
    image: mysql:8.0
    container_name: moodle_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=vaed3ui4yae4Vu
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodleuser
      - MYSQL_PASSWORD=meeF9av3geegh9
      - TZ=America/Sao_Paulo
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./vol/mysql/data:/var/lib/mysql
      - ./vol/mysql/my.cnf:/etc/my.cnf
      - ./vol/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize the database with the custom SQL script
    networks:
      - moodle_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: moodle_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=moodleuser
      - PMA_PASSWORD=meeF9av3geegh9
      - PMA_DATABASE=moodle
      - MYSQL_ROOT_PASSWORD=rootpassword
    depends_on:
      - db
    networks:
      - moodle_network
  phpu_db:
    image: mysql:8.0
    container_name: phpu_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=aecaathah9heiP
      - MYSQL_DATABASE=phpu
      - MYSQL_USER=phpu
      - MYSQL_PASSWORD=aecaathah9heiP
      - TZ=America/Sao_Paulo
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./vol/phpu/mysql/data:/var/lib/mysql
      - ./vol/phpu/mysql/my.cnf:/etc/my.cnf
      - ./vol/phpu/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize the database with the custom SQL script
    networks:
      - moodle_network

networks:
  moodle_network:
