services:
  db_slave:
    # image: mysql:8.0
    build:
      context: ./docker-files/db/mysql
    container_name: ${STACK_NAME}_db_slave
    restart: always
    # ports:
    #   - "${MYSQL_DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
      - MASTER_DB_HOST=db
    volumes:
      - ${STACK_VOLUME_DB}/slave/${DBTYPE}/data:/var/lib/mysql
      - ./config/db/slave/mysql/my.cnf:/etc/mysql/conf.d/my.local.cnf
      - ./config/db/slave/mysql/init.sql.template:/init.sql.template
      - ./config/db/slave/mysql/custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
    entrypoint: ["/custom-docker-entrypoint.sh"]
    networks:
      - pma_network
      - db_slave_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

networks:
  pma_network:
    external: true
    name: ${STACK_NAME}_pma_network
  db_slave_network:
    external: true
    name: ${STACK_NAME}_db_slave_network
