services:
  db_phpunit:
    # image: mysql:8.0
    build:
      context: ./docker-files/db/mysql
    container_name: ${STACK_NAME}_phpunit_db
    restart: always
    # ports:
    #   - "${PHPU_MYSQL_DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${PHPU_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${PHPU_MYSQL_DATABASE}
      - MYSQL_USER=${PHPU_MYSQL_USER}
      - MYSQL_PASSWORD=${PHPU_MYSQL_PASSWORD}
      - TZ=${TZ}
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${STACK_VOLUME_DB}/phpunit/${DBTYPE}/data:/var/lib/mysql
      - ./config/db/phpunit/mysql/my.cnf:/etc/my.cnf
      - ./config/db/phpunit/mysql/init.sql.template:/init.sql.template
      - ./config/db/phpunit/mysql/custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
    entrypoint: ["/custom-docker-entrypoint.sh"]
    networks:
      - db_phpunit_network
      - pma_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
networks:
  pma_network:
    external: true
    name: ${STACK_NAME}_pma_network
  db_phpunit_network:
    external: true
    name: ${STACK_NAME}_db_phpunit_network
