services:
  web:
    image: ${REPO}-${WEBSERVER}
    container_name: ${STACK}_moodle_web
    restart: always
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - ./src:/var/www/html
      - ./config/moodle/config.mysql.php:/var/www/html/config.php
      - ${VOLUME_DIR}/moodle/data:/var/www/moodledata
      - ${VOLUME_DIR}/phpunit/moodle/data:/var/www/phpu_moodledata
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PREFIX=${MYSQL_PREFIX}
      - MYSQL_PORT=${MYSQL_PORT}
      - WEB_PORT=${WEB_PORT}
      - SERVERURL=${SERVERURL}
      - WWWROOT=${WWWROOT}
      - SERVERURL=${SERVERURL}
      - WWWROOT=${WWWROOT}
      - PHPU_ENABLED=${PHPU_ENABLED}
      - PHPU_MYSQL_PREFIX=${PHPU_MYSQL_PREFIX}
      - PHPU_MYSQL_DATABASE=${PHPU_MYSQL_DATABASE}
      - PHPU_MYSQL_USER=${PHPU_MYSQL_USER}
      - PHPU_MYSQL_PASSWORD=${PHPU_MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - moodle_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

  db:
    image: mysql:8.0
    container_name: ${STACK}_moodle_db
    restart: always
    # ports:
    #   - "${MYSQL_DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${MYSQL_TZ}
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${VOLUME_DIR}/mysql/data:/var/lib/mysql
      - ./config/db/mysql/my.cnf:/etc/my.cnf
      - ./config/db/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - moodle_network

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${STACK}_moodle_phpmyadmin
    restart: always
    ports:
      - "${MYSQL_PMA_PORT}:80"
    environment:
      - PMA_HOST=db
      # - PMA_USER=${MYSQL_PMA_USER}
      # - PMA_PASSWORD=${MYSQL_PMA_PASSWORD}
      # - PMA_DATABASE=${MYSQL_PMA_DATABASE}
      # - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - moodle_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

  phpu_db:
    image: mysql:8.0
    container_name: ${STACK}_moodle_phpunit_db
    restart: always
    # ports:
    #   - "${MYSQL_PHPU_DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${PHPU_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${PHPU_MYSQL_DATABASE}
      - MYSQL_USER=${PHPU_MYSQL_USER}
      - MYSQL_PASSWORD=${PHPU_MYSQL_PASSWORD}
      - TZ=${PHPU_MYSQL_TZ}
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${VOLUME_DIR}/phpunit/mysql/data:/var/lib/mysql
      - ./config/phpunit/mysql/my.cnf:/etc/my.cnf
      - ./config/phpunit/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - moodle_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

  phpu_pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${STACK}_moodle_phpunit_phpmyadmin
    restart: always
    ports:
      - "${MYSQL_PHPU_PMA_PORT}:80"
    environment:
      - PMA_HOST=phpu_db
      # - PMA_DATABASE=${PHPU_MYSQL_PMA_DATABASE}
      # - PMA_USER=${PHPU_MYSQL_PMA_USER}
      # - PMA_PASSWORD=${PHPU_MYSQL_PMA_PASSWORD}
      # - MYSQL_ROOT_PASSWORD=${PHPU_MYSQL_ROOT_PASSWORD}
    depends_on:
      - phpu_db
    networks:
      - moodle_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

networks:
  moodle_network:
