services:
  web:
    image: ${REPO}-${WEBSERVER}
    container_name: ${STACK}_moodle_web
    restart: always
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
      - "${WEBS_PORT}:${WEBS_PORT}"
    volumes:
      - ./src:/var/www/html
      - ./config/moodle/config.mysql.php:/var/www/html/config.php
      - ${VOLUME_DIR}/moodle/data:/var/www/moodledata
      - ${VOLUME_DIR}/phpunit/moodle/data:/var/www/phpu_moodledata
      - ${VOLUME_DIR}/moodle/certbot/www/:/var/www/certbot/:rw
      - ${VOLUME_DIR}/moodle/certbot/conf/:/etc/letsencrypt/:rw
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PREFIX=${MYSQL_PREFIX}
      - MYSQL_PORT=${MYSQL_PORT}
      - FORCE_DEBUG=${FORCE_DEBUG}
      - WEBSERVER=${WEBSERVER}
      - WEB_PORT=${WEB_PORT}
      - WEBS_PORT=${WEBS_PORT}
      - DOMAIN=${DOMAIN}
      - CERT_COUNTRY=${CERT_COUNTRY}
      - CERT_STATE=${CERT_STATE}
      - CERT_CITY=${CERT_CITY}
      - CERT_ORG=${CERT_ORG}
      - CERT_ORG_UNIT=${CERT_ORG_UNIT}
      - SERVERURL=${SERVERURL}
      - WWWROOT=${WWWROOT}
      - SERVERURL=${SERVERURL}
      - WWWROOT=${WWWROOT}
      - TZ=${TZ}
      - PHPU_ENABLED=${PHPU_ENABLED}
      - PHPU_MYSQL_PREFIX=${PHPU_MYSQL_PREFIX}
      - PHPU_MYSQL_DATABASE=${PHPU_MYSQL_DATABASE}
      - PHPU_MYSQL_USER=${PHPU_MYSQL_USER}
      - PHPU_MYSQL_PASSWORD=${PHPU_MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - moodle_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
  certbot:
    image: certbot/certbot:latest
    container_name: ${STACK}_moodle_certbot
    networks:
      - moodle_network
    depends_on:
      - web
    volumes:
      - ${VOLUME_DIR}/moodle/certbot/www/:/var/www/certbot/:rw
      - ${VOLUME_DIR}/moodle/certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  db:
    image: mysql:8.0
    container_name: ${STACK}_moodle_db
    restart: always
    # ports:
    #   - "${MYSQL_DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${MYSQL_TZ}
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${VOLUME_DIR}/mysql/data:/var/lib/mysql
      - ./config/db/mysql/my.cnf:/etc/my.cnf
      - ./config/db/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - moodle_network

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${STACK}_moodle_phpmyadmin
    restart: always
    ports:
      - "${MYSQL_PMA_PORT}:80"
    environment:
      - PMA_HOST=db
      # - PMA_USER=${MYSQL_PMA_USER}
      # - PMA_PASSWORD=${MYSQL_PMA_PASSWORD}
      # - PMA_DATABASE=${MYSQL_PMA_DATABASE}
      # - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - moodle_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

  phpu_db:
    image: mysql:8.0
    container_name: ${STACK}_moodle_phpunit_db
    restart: always
    # ports:
    #   - "${MYSQL_PHPU_DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${PHPU_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${PHPU_MYSQL_DATABASE}
      - MYSQL_USER=${PHPU_MYSQL_USER}
      - MYSQL_PASSWORD=${PHPU_MYSQL_PASSWORD}
      - TZ=${PHPU_MYSQL_TZ}
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${VOLUME_DIR}/phpunit/mysql/data:/var/lib/mysql
      - ./config/phpunit/mysql/my.cnf:/etc/my.cnf
      - ./config/phpunit/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - moodle_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

  phpu_pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${STACK}_moodle_phpunit_phpmyadmin
    restart: always
    ports:
      - "${MYSQL_PHPU_PMA_PORT}:80"
    environment:
      - PMA_HOST=phpu_db
      # - PMA_DATABASE=${PHPU_MYSQL_PMA_DATABASE}
      # - PMA_USER=${PHPU_MYSQL_PMA_USER}
      # - PMA_PASSWORD=${PHPU_MYSQL_PMA_PASSWORD}
      # - MYSQL_ROOT_PASSWORD=${PHPU_MYSQL_ROOT_PASSWORD}
    depends_on:
      - phpu_db
    networks:
      - moodle_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

networks:
  moodle_network:
