services:
  web:
    image: ${REPO}-${WEBSERVER}
    container_name: ${STACK_NAME}_web
    restart: always
    ports:
      - "${HOST_IP}:${WEB_PORT}:${WEB_PORT}"
      - "${HOST_IP}:${WEBS_PORT}:${WEBS_PORT}"
    volumes:
      - ${STACK_SRC}:/var/www/html
      - ./config/moodle/config.mariadb.php:/var/www/html/config.php
      - ${STACK_VOLUME}/moodle/data:/var/www/moodledata
      - ${STACK_VOLUME}/phpunit/moodle/data:/var/www/phpu_moodledata
      - ${STACK_VOLUME}/moodle/certbot/www/:/var/www/certbot/:rw
      - ${STACK_VOLUME}/moodle/certbot/conf/:/etc/letsencrypt/:rw
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_PREFIX=${MARIADB_PREFIX}
      - MARIADB_PORT=${MARIADB_PORT}
      - FORCE_DEBUG=${FORCE_DEBUG}
      - WEBSERVER=${WEBSERVER}
      - WEB_PORT=${WEB_PORT}
      - WEBS_PORT=${WEBS_PORT}
      - DOMAIN=${DOMAIN}
      - CERT_COUNTRY=${CERT_COUNTRY}
      - CERT_STATE=${CERT_STATE}
      - CERT_CITY=${CERT_CITY}
      - CERT_ORG=${CERT_ORG}
      - CERT_ORG_UNIT=${CERT_ORG_UNIT}
      - SERVERURL=${SERVERURL}
      - WWWROOT=${WWWROOT}
      - SERVERURL=${SERVERURL}
      - WWWROOT=${WWWROOT}
      - TZ=${TZ}
      - PHPU_ENABLED=${PHPU_ENABLED}
      - PHPU_MARIADB_PREFIX=${PHPU_MARIADB_PREFIX}
      - PHPU_MARIADB_DATABASE=${PHPU_MARIADB_DATABASE}
      - PHPU_MARIADB_USER=${PHPU_MARIADB_USER}
      - PHPU_MARIADB_PASSWORD=${PHPU_MARIADB_PASSWORD}
    depends_on:
      - db
    networks:
      - moodle_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
  certbot:
    image: certbot/certbot:latest
    container_name: ${STACK_NAME}_certbot
    restart: always
    networks:
      - moodle_network
    depends_on:
      - web
    volumes:
      - ${STACK_VOLUME}/moodle/certbot/www/:/var/www/certbot/:rw
      - ${STACK_VOLUME}/moodle/certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  db:
    # image: mariadb:10.6
    build:
      context: ./docker-files/db/mariadb
    container_name: ${STACK_NAME}_db
    restart: always
    # ports:
    #   - "${MARIADB_DB_PORT}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - TZ=${TZ}
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${STACK_VOLUME}/mariadb/data:/var/lib/mysql
      - ./config/db/mariadb/my.cnf:/etc/my.cnf
      - ./config/db/mariadb/init.sql.template:/init.sql.template
      - ./config/db/mariadb/custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
    entrypoint: ["/custom-docker-entrypoint.sh"]
    networks:
      - moodle_network
      - pma_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${STACK_NAME}_phpmyadmin
    restart: always
    ports:
      - "${MARIADB_PMA_PORT}:80"
      - "${MARIADB_PMAS_PORT}:443"
    environment:
      - PMA_HOST=db

      # Careful: Uncomment these will expose your phpmyadmin login.
      # - PMA_USER=${MARIADB_USER}
      # - PMA_PASSWORD=${MARIADB_PASSWORD}
      # - PMA_DATABASE=${MARIADB_DATABASE}
      # - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    command: >
      sh -c "sed 's|/etc/ssl/certs/ssl-cert-snakeoil.pem|/etc/letsencrypt/fullchain.pem|g' /etc/apache2/sites-available/default-ssl.conf > /tmp/default-ssl.conf &&
            sed -i 's|/etc/ssl/private/ssl-cert-snakeoil.key|/etc/letsencrypt/privkey.pem|g' /tmp/default-ssl.conf &&
            mv /tmp/default-ssl.conf /etc/apache2/sites-available/default-ssl.conf &&
            if [ ! -f /etc/phpmyadmin/config.secret.inc.php ]; then
              echo \"<?php\\n\\\$$cfg['blowfish_secret'] = '$(php -r 'echo bin2hex(random_bytes(32));')';\" > /etc/phpmyadmin/config.secret.inc.php;
            fi && 
            apache2ctl -D FOREGROUND &
            while true; do
                sleep 12h
                apache2ctl graceful
            done
        "
    depends_on:
      - db
    networks:
      - pma_network
    volumes:
      - ${STACK_VOLUME}/moodle/certbot/conf/live/${DOMAIN}/:/etc/letsencrypt/:ro
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

  phpu_db:
    # image: mariadb:10.6
    build:
      context: ./docker-files/db/mariadb
    container_name: ${STACK_NAME}_phpunit_db
    restart: always
    # ports:
    #   - "${PHPU_MARIADB_DB_PORT}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${PHPU_MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${PHPU_MARIADB_DATABASE}
      - MARIADB_USER=${PHPU_MARIADB_USER}
      - MARIADB_PASSWORD=${PHPU_MARIADB_PASSWORD}
      - TZ=${TZ}
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${STACK_VOLUME}/phpunit/mariadb/data:/var/lib/mysql
      - ./config/phpunit/mariadb/my.cnf:/etc/my.cnf
      - ./config/db/mariadb/init.sql.template:/init.sql.template
      - ./config/db/mariadb/custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
    entrypoint: ["/custom-docker-entrypoint.sh"]
    networks:
      - moodle_network
      - phpu_pma_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

  phpu_pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${STACK_NAME}_phpunit_phpmyadmin
    restart: always
    ports:
      - "${PHPU_MARIADB_PMA_PORT}:80"
      - "${PHPU_MARIADB_PMAS_PORT}:443"
    environment:
      - PMA_HOST=phpu_db

      # Careful: Uncomment these will expose your phpmyadmin login.
      # - PMA_USER=${PHPU_MARIADB_USER}
      # - PMA_PASSWORD=${PHPU_MARIADB_PASSWORD}
      # - PMA_DATABASE=${PHPU_MARIADB_DATABASE}
      # - MARIADB_ROOT_PASSWORD=${PHPU_MARIADB_ROOT_PASSWORD}
    command: >
      sh -c "sed 's|/etc/ssl/certs/ssl-cert-snakeoil.pem|/etc/letsencrypt/fullchain.pem|g' /etc/apache2/sites-available/default-ssl.conf > /tmp/default-ssl.conf &&
            sed -i 's|/etc/ssl/private/ssl-cert-snakeoil.key|/etc/letsencrypt/privkey.pem|g' /tmp/default-ssl.conf &&
            mv /tmp/default-ssl.conf /etc/apache2/sites-available/default-ssl.conf &&
            if [ ! -f /etc/phpmyadmin/config.secret.inc.php ]; then
              echo \"<?php\\n\\\$$cfg['blowfish_secret'] = '$(php -r 'echo bin2hex(random_bytes(32));')';\" > /etc/phpmyadmin/config.secret.inc.php;
            fi && 
            apache2ctl -D FOREGROUND &
            while true; do
                sleep 12h
                apache2ctl graceful
            done
        "
    depends_on:
      - db
    networks:
      - phpu_pma_network
    volumes:
      - ${STACK_VOLUME}/moodle/certbot/conf/live/${DOMAIN}/:/etc/letsencrypt/:ro
      # - ${STACK_VOLUME}/moodle/certbot/conf/live/${DOMAIN}/fullchain.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem:ro
      # - ${STACK_VOLUME}/moodle/certbot/conf/live/${DOMAIN}/privkey.pem:/etc/ssl/private/ssl-cert-snakeoil.key:ro
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

networks:
  moodle_network:
  pma_network:
  phpu_pma_network:
