services:
  web:
    image: ${REPO}-${WEBSERVER}
    container_name: ${STACK}_moodle_web
    restart: always
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
      - "${WEBS_PORT}:${WEBS_PORT}"
    volumes:
      - ./src:/var/www/html
      - ./config/moodle/config.pgsql.php:/var/www/html/config.php
      - ${VOLUME_DIR}/moodle/data:/var/www/moodledata
      - ${VOLUME_DIR}/phpunit/moodle/data:/var/www/phpu_moodledata
    environment:
      - PGSQL_DB=${PGSQL_DB}
      - PGSQL_USER=${PGSQL_USER}
      - PGSQL_PASSWORD=${PGSQL_PASSWORD}
      - PGSQL_PREFIX=${PGSQL_PREFIX}
      - PGSQL_PORT=${PGSQL_PORT}
      - WEB_PORT=${WEB_PORT}
      - WEBS_PORT=${WEBS_PORT}
      - DOMAIN=${DOMAIN}
      - FORCE_DEBUG=${FORCE_DEBUG}
      - SERVERURL=${SERVERURL}
      - WWWROOT=${WWWROOT}
      - SERVERURL=${SERVERURL}
      - WWWROOT=${WWWROOT}
      - TZ=${TZ}
      - PHPU_ENABLED=${PHPU_ENABLED}
      - PHPU_PGSQL_PREFIX=${PHPU_PGSQL_PREFIX}
      - PHPU_PGSQL_DB=${PHPU_PGSQL_DB}
      - PHPU_PGSQL_USER=${PHPU_PGSQL_USER}
      - PHPU_PGSQL_PASSWORD=${PHPU_PGSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - moodle_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

  db:
    image: postgres:13
    container_name: ${STACK}_moodle_db
    restart: always
    # ports:
    #   - "${PGSQL_PORT}:5432"
    environment:
      - POSTGRES_DB=${PGSQL_DB}
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_PASSWORD}
      - TZ=${PGSQL_TZ}
    volumes:
      - ${VOLUME_DIR}/pgsql/data:/var/lib/postgresql/data
      - ./config/db/pgsql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - moodle_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

  phpu_db:
    image: postgres:13
    container_name: ${STACK}_moodle_phpunit_db
    restart: always
    # ports:
    #   - "${PHPU_PGSQL_PORT}:5432"
    environment:
      - POSTGRES_DB=${PHPU_PGSQL_DB}
      - POSTGRES_USER=${PHPU_PGSQL_USER}
      - POSTGRES_PASSWORD=${PHPU_PGSQL_PASSWORD}
      - TZ=${PHPU_PGSQL_TZ}
    volumes:
      - ${VOLUME_DIR}/phpunit/pgsql/data:/var/lib/postgresql/data
      - ${VOLUME_DIR}/phpunit/pgsql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - moodle_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: ${STACK}_moodle_pgadmin_db
    ports:
      - "${PGSQL_PGA_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=True
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    entrypoint: > 
      sh -c "
      chmod 600 /pgpass; /entrypoint.sh;
      "
    user: root
    depends_on:
      - db
      - phpu_db
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass
    networks:
      - moodle_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

configs:
  pgpass:
    content: |
      db:5432:${PGSQL_DB}:${PGSQL_USER}:${PGSQL_PASSWORD}
      phpu_db:5432:${PHPU_PGSQL_DB}:${PHPU_PGSQL_USER}:${PHPU_PGSQL_PASSWORD}
  servers.json:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "Moodle DB",
        "Host": "db",
        "Port": 5432,
        "MaintenanceDB": "${PGSQL_DB}",
        "Username": "${PGSQL_USER}",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      },"2": {
        "Group": "Servers",
        "Name": "PHPU DB",
        "Host": "phpu_db",
        "Port": 5432,
        "MaintenanceDB": "${PHPU_PGSQL_DB}",
        "Username": "${PHPU_PGSQL_USER}",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }}}

networks:
  moodle_network: