services:
  web:
    image: ${REPO}-${WEBSERVER}
    container_name: ${STACK}_moodle_web
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - ./src:/var/www/html
      - ./config/moodle/config.mariadb.php:/var/www/html/config.php
      - ${VOLUME_DIR}/moodle/data:/var/www/moodledata
      - ${VOLUME_DIR}/phpunit/moodle/data:/var/www/phpu_moodledata
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_PREFIX=${MARIADB_PREFIX}
      - MARIADB_PORT=${MARIADB_PORT}
      - WEB_PORT=${WEB_PORT}
      - SERVERURL=${SERVERURL}
      - WWWROOT=${WWWROOT}
      - SERVERURL=${SERVERURL}
      - WWWROOT=${WWWROOT}
      - PHPU_ENABLED=${PHPU_ENABLED}
      - PHPU_MARIADB_PREFIX=${PHPU_MARIADB_PREFIX}
      - PHPU_MARIADB_DATABASE=${PHPU_MARIADB_DATABASE}
      - PHPU_MARIADB_USER=${PHPU_MARIADB_USER}
      - PHPU_MARIADB_PASSWORD=${PHPU_MARIADB_PASSWORD}
    depends_on:
      - db
    networks:
      - moodle_network

  db:
    image: mariadb:10.6
    container_name: ${STACK}_moodle_db
    restart: always
    # ports:
    #   - "${MARIADB_DB_PORT}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - TZ=${MARIADB_TZ}
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${VOLUME_DIR}/mariadb/data:/var/lib/mysql
      - ./config/db/mariadb/my.cnf:/etc/my.cnf
      - ./config/db/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./backup/mariadb:/var/mariadb/backup/
    networks:
      - moodle_network

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${STACK}_moodle_phpmyadmin
    restart: always
    ports:
      - "${MARIADB_PMA_PORT}:80"
    environment:
      - PMA_HOST=db
      # - PMA_USER=${MARIADB_PMA_USER}
      # - PMA_PASSWORD=${MARIADB_PMA_PASSWORD}
      # - PMA_DATABASE=${MARIADB_PMA_DATABASE}
      # - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - moodle_network

  phpu_db:
    image: mariadb:10.6
    container_name: ${STACK}_moodle_phpunit_db
    restart: always
    # ports:
    #   - "${MARIADB_PHPU_DB_PORT}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${PHPU_MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${PHPU_MARIADB_DATABASE}
      - MARIADB_USER=${PHPU_MARIADB_USER}
      - MARIADB_PASSWORD=${PHPU_MARIADB_PASSWORD}
      - TZ=${PHPU_MARIADB_TZ}
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${VOLUME_DIR}/phpunit/mariadb/data:/var/lib/mariadb
      - ./config/phpunit/mariadb/my.cnf:/etc/my.cnf
      - ./config/phpunit/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - moodle_network

  phpu_pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${STACK}_moodle_phpunit_phpmyadmin
    restart: always
    ports:
      - "${MARIADB_PHPU_PMA_PORT}:80"
    environment:
      - PMA_HOST=phpu_db
      # - PMA_DATABASE=${PHPU_MARIADB_PMA_DATABASE}
      # - PMA_USER=${PHPU_MARIADB_PMA_USER}
      # - PMA_PASSWORD=${PHPU_MARIADB_PMA_PASSWORD}
      # - MARIADB_ROOT_PASSWORD=${PHPU_MARIADB_ROOT_PASSWORD}
    depends_on:
      - phpu_db
    networks:
      - moodle_network

networks:
  moodle_network:
