services:
  db_slave:
    # image: postgres:13
    build:
      context: ./docker-files/db/pgsql
    container_name: ${STACK_NAME}_db_slave
    restart: always
    # ports:
    #   - "${PGSQL_PORT}:5432"
    environment:
      - POSTGRES_DB=${PGSQL_DB}
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ${STACK_VOLUME_DB}/master/${DBTYPE}/data:/var/lib/postgresql/data
      - ./config/db/master/pgsql/init.sql.template:/init.sql.template
      - ./config/db/master/pgsql/custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
    entrypoint: ["/custom-docker-entrypoint.sh"]
    networks:
      - db_slave_network
      - pgadmin_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
networks:
  db_slave_network:
    external: true
    name: ${STACK_NAME}_db_slave_network
  pgadmin_network:
    external: true
    name: ${STACK_NAME}_pgadmin_network