services:
  db_phpunit:
    # image: postgres:13
    build:
      context: ./docker-files/db/pgsql
    container_name: ${STACK_NAME}_phpunit_db
    restart: always
    # ports:
    #   - "${PHPU_PGSQL_PORT}:5432"
    environment:
      - POSTGRES_DB=${PHPU_PGSQL_DB}
      - POSTGRES_USER=${PHPU_PGSQL_USER}
      - POSTGRES_PASSWORD=${PHPU_PGSQL_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ${STACK_VOLUME_DB}/phpunit/${DBTYPE}/data:/var/lib/postgresql/data
      - ./config/db/phpunit/pgsql/init.sql.template:/init.sql.template
      - ./config/db/phpunit/pgsql/custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
    entrypoint: ["/custom-docker-entrypoint.sh"]
    networks:
      - db_phpunit_network
      - pgadmin_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

networks:
  db_phpunit_network:
    external: true
    name: ${STACK_NAME}_db_phpunit_network
  pgadmin_network:
    external: true
    name: ${STACK_NAME}_pgadmin_network